Repository Brigoon/DumbBot, pull requests merged in 2021-11, with the labels that each got.

#10 Added stipe message reaction and cleaned up message comments
  .gitignore
  dumbbot.py
Labels: enhancement

#12 Better input checking and f print
  dumbbot.py
Labels: documentation

#13 Weather
  dumbbot.py
  weather.py
Labels: documentation, enhancement

#14 Change bot output to one long string and add bold text
  weather.py
Labels: documentation, enhancement

#16 Herald base functionality
  .gitignore
  dumbbot.py
  helper.py
  herald.py
  text/approved.txt
  text/both_need.txt
  text/brian_dex.txt
  text/brian_need.txt
  text/jake_dex.txt
  text/jake_need.txt
  text/pokedex_gen1.txt
  text/pokedex_gen2.txt
  text/pokedex_gen3.txt
  text/ty_dex.txt
  text/ty_need.txt
Labels: documentation, enhancement

#20 Herald start time and other fixes
  herald.py
Labels: bug, enhancement

#21 Herald voice channel delay
  .gitignore
  herald.py
Labels: enhancement
